### ISSUE TITLE
Can't install word-count environment from requirements.txt

### ISSUE THREAD

**Issue by bast** [coderefinery/reproducible-research#131]
This is what I get when installing from requirements.txt:
```
Collecting numpy==1.17.3
  Using cached numpy-1.17.3-cp38-cp38-manylinux1_x86_64.whl (20.5 MB)
Collecting matplotlib==3.1.1
  Using cached matplotlib-3.1.1.tar.gz (37.8 MB)
ERROR: Could not find a version that satisfies the requirement snakemake-minimal==5.8.1 (from -r requirements.txt (line 3)) (from versions: none)
ERROR: No matching distribution found for snakemake-minimal==5.8.1 (from -r requirements.txt (line 3))
```

**Comment by johanhellsvik** [comment]
I also encountered problems on one of my computers. We need to get back to this issue.

**Comment by bast** [comment]
Also please check whether this is in sync with the `requirements.txt` in https://github.com/coderefinery/software. There at least the installation seems to work (checked by GH Actions, I haven't tried this locally yet again).

**Comment by wikfeldt** [comment]
no requirements.txt file is used in this lesson any longer. `snakemake-minimal=6.2.1` is included in the environment.yml file on https://github.com/coderefinery/software and hopefully this means that snakemake-minimal has been successfully installed by learners in workshops since the current issue was opened. (on my mac it installs without problem)

nothing to do here so closing issue
