### ISSUE TITLE
use tracked data and source code under project directory in episode 03?

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/reproducible-research#3]
In episode 3, the learner is instructed to clone the bast/make-pipeline repo somewhere, and then later copy the datafiles and source files to a project directory. Would it be better (more realistic and a better practice) to create a separate repo which already has the correct directory structure, so that the example project directory is already a git repo?

**Comment by bast** [comment]
@Vathasav also we need to decide where we do that make part. If this is moved to a different session, please inform me about it. Until further notice I assume that this is still part of the CMake session. Any solution is fine but we need to communicate about it.

**Comment by Vathasav** [comment]
In episode 3 I have introduced make and have covered most of the points you have mentioned in the  make introduction. I will try to cover other points you mentioned. @bast we can remove the make introduction in CMake session, as you are not using it any other episodes.

**Comment by bast** [comment]
OK - I will keep it in the CMake material for the moment but probably then skip it next week when teaching. Later, we can possibly completely remove it but it may make sense to have it there if CMake is treated independently since it provides (IMO) a nice introduction to it. It is not important for me that you cover everything that I have mentioned in the make part - cover the things that you find important to cover.

**Comment by bast** [comment]
But sorry for distracting from the actual question (first post).
