### ISSUE TITLE
Forking is not necessary for snakemake tutorial

### ISSUE THREAD

**Issue by tprossi** [coderefinery/reproducible-research#58]
Snakemake tutorial starts by forking https://github.com/coderefinery/word-count but one can clone the project directly without forking. This would make tutorial smoother when snakemake is taught before collaborative git.

**Comment by wikfeldt** [comment]
thanks for noting this down. Forking is not needed in reproducibility, but it is in the documentation lesson. so the problem is that:
- we clone word-count in git-intro for digging through history (see https://github.com/coderefinery/git-intro/issues/157)
- we need to fork and clone coderefinery/word-count in documentation
- we now want to teach reproducibility before git-collaborative, and we need word-count in reproducibility lesson. Cloning word-count in reproducibility would lead to the same confusion about forking it in documentation, but forking it instead might be confusing because we haven't yet talked about forking

Either we ask learners to remove the cloned word-count repo locally before forking/cloning it during documentation, or we ask them to change the remote from coderefinery/word-count to user/word-count.

**Comment by bast** [comment]
I recommend that we only clone within this lesson but then for the documentation lesson we fork and clone the fork. By that time both concepts are familiar and we can spend 2 minutes explaining why we fork at documentation lesson stage.

**Comment by annefou** [comment]
The simplest is to remove the cloned word-count repo at the end of the lesson so the lessons can be taught in any order. Maybe it is also a good idea to show that there is no need to keep all these cloned repositories when not needed (cleaning/removing is usually forgotten in Data Management Plans).

**Comment by rkdarst** [comment]
It seems to me like the idea of just cloning, and then removing and forking later is the simplest answer.

Is there any need to leave a mention of forking here?  Can we just, in the later cases that use this, give a note to delete any existing `word-count` clones?

**Comment by rkdarst** [comment]
Perhaps more importantly... this is used in git-intro (archeology), reproducible-research, and documentation.  Should all of them say to delete it if it already exists?  What lesson sequences do we support?

**Comment by bast** [comment]
> It seems to me like the idea of just cloning, and then removing and forking later is the simplest answer.
> 
> Is there any need to leave a mention of forking here? Can we just, in the later cases that use this, give a note to delete any existing `word-count` clones?

I agree with both.
